(The pre-print is in process and the paper will be published soon)

# Site-specific multilevel modeling of potato response to nitrogen fertilization
Serge-Étienne Parent1*, Michael Leblanc1, Annie-Claude Parent2, Zonlehoua Coulibali1, Léon Etienne Parent1
1. Department of Soils and Agrifood Engineering, Université Laval, Québec, Canada G1V0A6
2. Department of Civil and Water Engineering, Université Laval, Québec, Canada G1V0A6
* Corresponding author: Serge-Étienne Parent, email: serge-etienne.parent.1@ulaval.ca
 
## ABSTRACT
Technologies of precision agriculture, digital soil maps and meteorological stations provide a minimum data set to guide precision farming operations. However, determining optimal nutrient requirements for potato (Solanum tuberosum L.) crops at subfield scale remains a challenge given specific climatic, edaphic and managerial conditions. Multilevel modeling can generalize yield response to fertilizer additions using data easily accessible to growers. Our objective was to elaborate a multilevel N fertilizer recommendation model for potato crops using the Mitscherlich equation and a core data set of 93 N fertilizer trials conducted in Quebec, Canada. Daily climatic data were collected at 10 km 𝗑 10 km resolution. Soils were characterized by organic matter content, pH and texture in the arable layer, and by texture and tools of pedometrics across a gleization-podzolization continuum in subsoil layers. There were five categories of preceding crops and five cultivar maturity orders. The three Mitscherlich parameters (Asymptote, Rate and Environment) were most often site-specific as predicted by Liebscher’s law of optimum. Sensitivity analysis showed that potato optimum N dosage increased with non-leguminous high-residue preceding crops, coarser soils, podzolization, drier climatic condition and late cultivar maturity. The inferential model could be programmed as a predictive model to guide site-specific N fertilization using an accessible minimum data set, but would require more field trials and response curve adjustments to support fertilization decisions. The model as decision-support system could provide a range of optimum N doses across a large spectrum of site-specific conditions.
